### ISSUE TITLE
Use a valid json format to store cookies.

### ISSUE THREAD

**Issue by dcampbell24** [pfernie/reqwest_cookie_store#10]
You can't parse the cookies with ` let cookies: serde_json::Value = serde_json::from_str(&data).unwrap();`, because you store the cookies in an invalid json format. Why not just stick the cookies in an Array?

**Comment by pfernie** [comment]
The de/serialization behavior here is actually implemented in the underlying [cookie_store](https://github.com/pfernie/cookie_store) crate. It is true the behavior there is line-oriented (serializing each cookie individually). The crate provides some methods that abstract over the serialization method, with the intent of supporting other formats such as the curl cookie file format and the like. In practice, JSON is the only target format that is used (AFAIK).

That being said, I wouldn't want to change the existing behavior of these methods as this would be breaking for current users/serialized cookie sets. I would be happy to review a PR (on [cookie_store](https://github.com/pfernie/cookie_store)) introducing alternative serializations, however.

**Comment by dcampbell24** [comment]
I created a [pull request](https://github.com/pfernie/cookie_store/pull/43) with some ideas.

**Comment by pfernie** [comment]
Closing as discussion is occurring on the [PR](https://github.com/pfernie/cookie_store/pull/43)
