### ISSUE TITLE
Is it example for CookieStore::load?

### ISSUE THREAD

**Issue by RustGrow** [pfernie/reqwest_cookie_store#11]
Can you add an example how to use CookieStore::load because It's lifetime errors.
cookie_store::CookieStore::load
cookie_store::CookieStore::load(file, serde_json::from_str).unwrap()

**Comment by pfernie** [comment]
Wrapping the `from_str` in a closure will address the lifetime issue:
```rust
cookie_store::CookieStore::load(file, |c| serde_json::from_str(c)).unwrap()
```
