### ISSUE TITLE
cookie.json is empty when write to disk

### ISSUE THREAD

**Issue by eribol** [pfernie/reqwest_cookie_store#7]
Everything works as expected but when i write cookies to disk, it is empty.
```
let store = cookie_store.lock().unwrap();

    for c in store.iter_any() {
        println!("{:?}", c);
    }
store.save_json(&mut writer).unwrap();
```
It write cookie right with println! but somehow its empty on disk when save_json write it.

**Comment by pfernie** [comment]
I'm not seeing that behavior locally; can you provide more detail of your setup and/or test code? This abbreviated version of the doctest sample behaves as expected:

```rust
#[tokio::main]
async fn main() {
    let cookie_store = cookie_store::CookieStore::new(None);
    let cookie_store = reqwest_cookie_store::CookieStoreMutex::new(cookie_store);
    let cookie_store = std::sync::Arc::new(cookie_store);
    {
        println!("initial state (should be empty!)");
        let store = cookie_store.lock().unwrap();
        for c in store.iter_any() {
            println!("{:?}", c);
        }
    }

    let client = reqwest::Client::builder()
        .cookie_provider(std::sync::Arc::clone(&cookie_store))
        .build()
        .unwrap();
    println!("fetching google.com");
    client.get("https://google.com").send().await.unwrap();
    println!("done fetching google.com");
    {
        println!("after google.com GET");
        let store = cookie_store.lock().unwrap();
        for c in store.iter_any() {
            println!("{:?}", c);
        }
        let mut writer = std::fs::File::create("cookies2.json")
            .map(std::io::BufWriter::new)
            .unwrap();
        store.save_json(&mut writer).unwrap();
    }
}
```

**Comment by eribol** [comment]
```rust
    let cookie_store = CookieStore::new(None);
    let cookie_store = reqwest_cookie_store::CookieStoreMutex::new(cookie_store);
    let cookie_store = std::sync::Arc::new(cookie_store);
    let cl = reqwest::Client::builder()
        .cookie_provider(std::sync::Arc::clone(&cookie_store))
        .build()
        .unwrap();
    let res = cl
        .post("http://192.168.1.101/login")
        .json(&form)
        .send()
        .await
        .unwrap();
    let mut writer: std::io::BufWriter<std::fs::File> = std::fs::File::create("cookie.json")
        .map(std::io::BufWriter::new)
        .unwrap();
    let store = cookie_store.lock().unwrap();

    for c in store.iter_any() {
         println!("{:?}", c);
    }
    store.save_json(&mut writer).unwrap();
```
It is all this. It creates a json file but it does not write any cookies. But store.iter() write cookies, store is not empty. This is what store have.
```
Cookie { raw_cookie: Cookie { cookie_string: Some("id=MGtyJSa2GHGaNyO%2FxoxE9q4fg%2FTPHrzvRwfoXWEOe25daWNk4z5AIIkS7DigXnMkZ5FVDLrEpaz9hq3GTbUzmqBbYpmYp8fsNTG223HokKxDYmPGUFsrmR4g%2Fyo%3D; HttpOnly; SameSite=Lax; Secure; Path=/"), name: Indexed(0, 2), value: Indexed(3, 135), expires: None, max_age: None, domain: None, path: Some(Indexed(174, 175)), secure: Some(true), http_only: Some(true), same_site: Some(Lax) }, path: CookiePath("/", true), domain: HostOnly("192.168.1.101"), expires: SessionEnd }
```

**Comment by eribol** [comment]
I do not know but, when i get google.com it works. why not for ip? Is there some standart i am not aware? It is a simple server created with actix-web and session middleware. It sends cookies, i printed it but it just do not write a file.

**Comment by pfernie** [comment]
The cookie being issued:
`Cookie { raw_cookie: Cookie { cookie_string: Some("id=MGtyJSa2GHGaNyO%2FxoxE9q4fg%2FTPHrzvRwfoXWEOe25daWNk4z5AIIkS7DigXnMkZ5FVDLrEpaz9hq3GTbUzmqBbYpmYp8fsNTG223HokKxDYmPGUFsrmR4g%2Fyo%3D; HttpOnly; SameSite=Lax; Secure; Path=/"), name: Indexed(0, 2), value: Indexed(3, 135), expires: None, max_age: None, domain: None, path: Some(Indexed(174, 175)), secure: Some(true), http_only: Some(true), same_site: Some(Lax) }, path: CookiePath("/", true), domain: HostOnly("192.168.1.101"), expires: SessionEnd }`

is not persistent (`expires: SessionEnd`). Per [RFC6265], such cookies:
```
   When "the current session is over" (as defined by the user agent),
   the user agent MUST remove from the cookie store all cookies with the
   persistent-flag set to false.
```

`CookieStore::save` [respects this](https://github.com/pfernie/cookie_store/blob/d0d10596740ee7dc3a6fcc320a911731983fb857/src/cookie_store.rs#L375-L379), and as such does not include non-persistent cookies when saving.

**Comment by eribol** [comment]
Yes, it was the only difference between google.com cookie. It should be fixed by backend i gues. Thank you.
